### PR TITLE
Support for generating cascades

### PR DESCRIPTION
**Pull request by reyostallenberg**

### CODE REVIEW

**Comment by reyostallenberg** [comment]
See https://github.com/FlexModel/FlexModel/pull/14

**Comment by reyostallenberg** [comment]
@niels-nijens what is the status of this?

**Review by niels-nijens — APPROVED** [review]

**Comment by niels-nijens** [comment]
Could you rebase your branch?

**Comment by reyostallenberg** [comment]
Rebase done

**Pull request merged**
