### PR TITLE
Also add default option to doctrine mappings when default_value is set

### PR DESCRIPTION
**Pull request by reyostallenberg**

### CODE REVIEW

**Comment by reyostallenberg** [comment]
This will ensure the default value for the column being set in doctrine orm entity configurations

**Comment by niels-nijens** [comment]
Can you provide a description of what specific use-case this solves? It's seems really specific for a project and according to Doctrine you can't add a default value to the doctrine entity mapping. See the [Doctrine FAQ](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/faq.html#how-can-i-add-default-values-to-a-column).

**Comment by reyostallenberg** [comment]
It is far from specific

If you have configured the default_value attribute on a field I think it's logical when the mysql database also has this value being set as default and also the generated private property of the doctrine entity.

Do you really need a use case?

**Comment by reyostallenberg** [comment]
The use case is that when constructing an entity you don't want to set the value of a property afterwards.
And when generating an entity you don't want have to do this manually afterwards.

**Pull request merged**
